name: Deploy

on:
  push:
    branches:
      - master # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH and deploy
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        ssh -i keyfile ubuntu@ec2-3-25-92-34.ap-southeast-2.compute.amazonaws.com	  <<EOF
        cd week-9
        git pull origin master
        cd server  
        pm2 kill  
        pm2 start index.js
EOF
