name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH directory
        run: mkdir -p ~/.ssh

      - name: Create SSH key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Add GitHub.com to known hosts
        run: ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: SSH and deploy
        run: ssh -i ~/.ssh/id_rsa ubuntu@ec2-3-104-64-52.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
